import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  Shield, TrendingUp, Building2, Coins, Users, Globe, Zap, ArrowUpRight, 
  BarChart3, PieChart, Activity, AlertTriangle, FileSpreadsheet, Download, RefreshCw, CheckCircle2, Lock
} from 'lucide-react';
import { useAuth } from '@/lib/AuthContext';
import { useToast } from '@/components/ui/use-toast';
import { Button } from '@/components/ui/button';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts';

const EXECUTIVE_SIGNALS = [
  {
    id: 'sig_1',
    type: 'MARKET',
    title: 'Demand for renewable-energy financing increased 18% this month',
    description: 'AI detected 46 relevant signals across companies and investment communities. Primary demand focused on utility-scale solar PV and storage.',
    confidence: 'HIGH',
    sourcesCount: 46,
    impact: 'POSITIVE',
    time: '2 hours ago'
  },
  {
    id: 'sig_2',
    type: 'INTERNATIONAL',
    title: '22 Tunisian SMEs currently seeking German distribution & technology partners',
    description: 'Bavarian & Baden-Württemberg trade corridors showing accelerated intent for AgriTech and automotive wire harness exports.',
    confidence: 'HIGH',
    sourcesCount: 22,
    impact: 'HIGH_OPPORTUNITY',
    time: '5 hours ago'
  },
  {
    id: 'sig_3',
    type: 'INVESTMENT',
    title: '14 new published projects with capital requirements exceeding €50M',
    description: 'Concentrated in Grand Tunis, Bizerte, and Sfax industrial corridors.',
    confidence: 'VERIFIED',
    sourcesCount: 14,
    impact: 'POSITIVE',
    time: '1 day ago'
  },
  {
    id: 'sig_4',
    type: 'RISK',
    title: 'Elevated sentiment around international logistics costs in manufacturing',
    description: 'Maritime freight rates and port lead time concerns cited in 12 recent corporate posts.',
    confidence: 'MEDIUM',
    sourcesCount: 12,
    impact: 'WARNING',
    time: '1 day ago'
  }
];

const SECTOR_GROWTH_DATA = [
  { sector: 'AI & Tech', capital: 120, deals: 45 },
  { sector: 'AgriTech', capital: 85, deals: 32 },
  { sector: 'Solar Energy', capital: 240, deals: 18 },
  { sector: 'Automotive EV', capital: 150, deals: 24 },
  { sector: 'Pharma Biotech', capital: 95, deals: 14 },
];

export default function ExecutiveIntelligence() {
  const { user } = useAuth();
  const { toast } = useToast();
  const [activeInstitution, setActiveInstitution] = useState('UTICA');
  const [refreshing, setRefreshing] = useState(false);

  const handleRefreshData = () => {
    setRefreshing(true);
    setTimeout(() => {
      setRefreshing(false);
      toast({
        title: '⚡ Intelligence Data Refreshed',
        description: 'Synchronized latest Economic Knowledge Graph signals from Feed & Circles.',
      });
    }, 1000);
  };

  const downloadBrief = () => {
    const lines = [
      `INVESTRADERS — EXECUTIVE INTELLIGENCE BRIEF`,
      `Date: ${new Date().toLocaleDateString()}`,
      `Institution Context: ${activeInstitution}`,
      ``,
      `KEY METRICS`,
      `- Companies Connected: 12,480`,
      `- Investment Opportunities: 1,284`,
      `- Capital Seeking: €4.8B`,
      `- Active Investors: 642`,
      `- International Matches: 3,812`,
      ``,
      `AI SIGNALS SUMMARY`,
      ...EXECUTIVE_SIGNALS.map(s => `[${s.type}] ${s.title} — ${s.description} (Sources: ${s.sourcesCount})`),
      ``,
      `Confidential & Proprietary — Generated by Investraders Economic Intelligence Engine`
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Investraders_Executive_Brief_${activeInstitution}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      
      {/* HEADER */}
      <div className="flex items-center justify-between flex-wrap gap-4 border-b pb-6">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-blue-600 via-purple-600 to-indigo-700 flex items-center justify-center text-white shadow-lg">
            <Shield className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-2xl font-black text-foreground">Executive Command Center</h1>
              <span className="px-2.5 py-0.5 rounded-md bg-purple-500/10 text-purple-600 dark:text-purple-400 border border-purple-500/20 text-xs font-bold">
                PRO / INSTITUTIONAL
              </span>
            </div>
            <p className="text-xs text-muted-foreground">
              Real-time economic sensor telemetry & macro investment signals for institutional leaders
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={handleRefreshData} disabled={refreshing}>
            <RefreshCw className={`w-4 h-4 mr-2 ${refreshing ? 'animate-spin' : ''}`} /> Refresh Signals
          </Button>
          <Button size="sm" className="bg-[#1769FF] hover:bg-blue-600 font-bold" onClick={downloadBrief}>
            <Download className="w-4 h-4 mr-2" /> Export Brief (PDF)
          </Button>
        </div>
      </div>

      {/* INSTITUTION CONTEXT SELECTOR */}
      <div className="flex items-center gap-2 overflow-x-auto pb-2">
        <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider shrink-0 mr-2">
          Institution Context:
        </span>
        {[
          { id: 'UTICA', label: 'UTICA Command' },
          { id: 'FIPA', label: 'TIA / FIPA FDI' },
          { id: 'CDC', label: 'CDC Sovereign Fund' },
          { id: 'CHAMBERS', label: 'International Chambers' },
          { id: 'BANKS', label: 'Commercial Banks' }
        ].map(inst => (
          <button
            key={inst.id}
            onClick={() => setActiveInstitution(inst.id)}
            className={`px-4 py-2 rounded-xl text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeInstitution === inst.id
                ? 'bg-primary text-primary-foreground shadow-md'
                : 'bg-card border text-muted-foreground hover:text-foreground'
            }`}
          >
            {inst.label}
          </button>
        ))}
      </div>

      {/* TOP KPI CARDS */}
      <div className="grid grid-cols-2 lg:grid-cols-5 gap-4">
        {[
          { label: 'Companies Connected', value: '12,480', sub: '+340 this month', icon: Building2, color: 'text-blue-500', bg: 'bg-blue-500/10' },
          { label: 'Investment Opportunities', value: '1,284', sub: 'Active pipeline', icon: Zap, color: 'text-amber-500', bg: 'bg-amber-500/10' },
          { label: 'Capital Seeking', value: '€4.8B', sub: 'Across 24 governorates', icon: Coins, color: 'text-[#20B26B]', bg: 'bg-emerald-500/10' },
          { label: 'Active Investors', value: '642', sub: 'EU, GCC & Regional', icon: Users, color: 'text-purple-500', bg: 'bg-purple-500/10' },
          { label: 'International Matches', value: '3,812', sub: 'AI verified connections', icon: Globe, color: 'text-[#16C7B7]', bg: 'bg-teal-500/10' },
        ].map(kpi => (
          <div key={kpi.label} className="rounded-2xl border bg-card p-4 space-y-2 shadow-sm hover:shadow-md transition-shadow">
            <div className={`w-9 h-9 rounded-xl ${kpi.bg} flex items-center justify-center ${kpi.color}`}>
              <kpi.icon className="w-5 h-5" />
            </div>
            <div>
              <div className="text-2xl font-black text-foreground">{kpi.value}</div>
              <div className="text-xs font-medium text-muted-foreground">{kpi.label}</div>
              <div className="text-[10px] text-muted-foreground/70 mt-0.5 font-mono">{kpi.sub}</div>
            </div>
          </div>
        ))}
      </div>

      {/* MAIN TWO COLUMN GRID */}
      <div className="grid lg:grid-cols-3 gap-8">
        
        {/* LEFT 2 COLS: REAL-TIME AI SIGNALS FEED */}
        <div className="lg:col-span-2 space-y-6">
          <div className="rounded-3xl border bg-card p-6 shadow-xl space-y-5">
            <div className="flex items-center justify-between border-b pb-4">
              <div>
                <h2 className="text-lg font-bold flex items-center gap-2">
                  <Activity className="w-5 h-5 text-primary" /> Real-Time Economic Sensor Signals
                </h2>
                <p className="text-xs text-muted-foreground mt-0.5">
                  AI extracted signals from daily company posts, circle exchanges & investment requests
                </p>
              </div>
              <span className="px-2.5 py-1 rounded-full bg-emerald-500/10 text-emerald-600 text-xs font-bold border border-emerald-500/20">
                LIVE SENSOR ACTIVE
              </span>
            </div>

            <div className="space-y-4">
              {EXECUTIVE_SIGNALS.map(sig => (
                <div key={sig.id} className="p-4 rounded-2xl border bg-muted/30 space-y-2 hover:border-primary/30 transition-colors">
                  <div className="flex items-center justify-between gap-2 flex-wrap">
                    <div className="flex items-center gap-2">
                      <span className={`px-2.5 py-0.5 rounded-md text-[10px] font-black uppercase tracking-wider ${
                        sig.impact === 'WARNING' ? 'bg-amber-500/20 text-amber-500 border border-amber-500/30' :
                        sig.impact === 'HIGH_OPPORTUNITY' ? 'bg-teal-500/20 text-teal-400 border border-teal-500/30' :
                        'bg-blue-500/20 text-blue-400 border border-blue-500/30'
                      }`}>
                        {sig.type}
                      </span>
                      <span className="text-xs font-bold text-foreground">{sig.title}</span>
                    </div>
                    <span className="text-[10px] text-muted-foreground font-mono">{sig.time}</span>
                  </div>

                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {sig.description}
                  </p>

                  <div className="flex items-center justify-between text-[11px] pt-1 text-muted-foreground border-t border-border/50">
                    <span>Source attribution: <strong>{sig.sourcesCount} verified platform signals</strong></span>
                    <span className="text-primary font-bold">Confidence: {sig.confidence} ✓</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* SECTOR CAPITAL ALLOCATION CHART */}
          <div className="rounded-3xl border bg-card p-6 shadow-xl space-y-4">
            <h3 className="font-bold text-base flex items-center gap-2">
              <BarChart3 className="w-5 h-5 text-primary" /> Sector Capital Seeking vs Deal Volume (€M)
            </h3>
            <div className="h-64 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={SECTOR_GROWTH_DATA} margin={{ top: 10, right: 10, left: -15, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" opacity={0.1} />
                  <XAxis dataKey="sector" tick={{ fontSize: 11 }} />
                  <YAxis tick={{ fontSize: 11 }} />
                  <Tooltip contentStyle={{ borderRadius: 12, fontSize: 12 }} />
                  <Bar dataKey="capital" fill="#1769FF" radius={[6, 6, 0, 0]} name="Capital Seeking (€M)" />
                  <Bar dataKey="deals" fill="#16C7B7" radius={[6, 6, 0, 0]} name="Deals Active" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        {/* RIGHT 1 COL: CROSS-BORDER CORRIDORS & INSTITUTIONAL ACTIONS */}
        <div className="space-y-6">
          
          {/* CROSS-BORDER FLOWS */}
          <div className="rounded-3xl border bg-card p-6 shadow-xl space-y-4">
            <h3 className="font-bold text-base flex items-center gap-2">
              <Globe className="w-5 h-5 text-primary" /> Cross-Border Economic Flows
            </h3>
            
            <div className="space-y-3">
              <div className="p-3.5 rounded-2xl border bg-muted/40 space-y-1">
                <div className="flex items-center justify-between text-xs font-bold">
                  <span>🇹🇳 Tunisia ↔ 🇪🇺 Europe</span>
                  <span className="text-primary">€1.4B Active Flow</span>
                </div>
                <div className="w-full bg-muted rounded-full h-2 overflow-hidden">
                  <div className="bg-[#1769FF] h-full rounded-full" style={{ width: '75%' }} />
                </div>
                <span className="text-[10px] text-muted-foreground block">Primary demand: Industrial sub-contracting & Green Tech</span>
              </div>

              <div className="p-3.5 rounded-2xl border bg-muted/40 space-y-1">
                <div className="flex items-center justify-between text-xs font-bold">
                  <span>🇹🇳 Tunisia ↔ 🌍 Sub-Saharan Africa</span>
                  <span className="text-[#16C7B7]">€850M Active Flow</span>
                </div>
                <div className="w-full bg-muted rounded-full h-2 overflow-hidden">
                  <div className="bg-[#16C7B7] h-full rounded-full" style={{ width: '55%' }} />
                </div>
                <span className="text-[10px] text-muted-foreground block">Primary demand: FinTech SaaS, Pharma & Higher Ed</span>
              </div>

              <div className="p-3.5 rounded-2xl border bg-muted/40 space-y-1">
                <div className="flex items-center justify-between text-xs font-bold">
                  <span>🇹🇳 Tunisia ↔ 🌴 GCC (Gulf)</span>
                  <span className="text-amber-500">€2.1B Active Flow</span>
                </div>
                <div className="w-full bg-muted rounded-full h-2 overflow-hidden">
                  <div className="bg-amber-500 h-full rounded-full" style={{ width: '90%' }} />
                </div>
                <span className="text-[10px] text-muted-foreground block">Primary demand: Solar infrastructure & Luxury Tourism</span>
              </div>
            </div>
          </div>

          {/* INSTITUTIONAL DATA GOVERNANCE NOTICE */}
          <div className="rounded-3xl border border-purple-500/30 bg-purple-500/5 p-6 space-y-3">
            <div className="flex items-center gap-2 text-purple-600 dark:text-purple-400 font-bold text-sm">
              <Lock className="w-4 h-4" /> Data Governance & Anonymization
            </div>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Institutional intelligence is aggregated from public signals, opt-in company profiles, and macro telemetry with strict privacy & consent controls.
            </p>
          </div>

        </div>

      </div>
    </div>
  );
}
